---
#
# kubernetes_minor_versions
# kraken_endpoint
#
- set_fact:
    cluster: "{{ a_cluster }}"

- name: Set kubeconfig path
  set_fact:
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"
#
# timing test... looks like we may have to setup rbac as soon as the apiservers are available..so the cluster can come up
#
- name: Setup initial readiness wait
  set_fact:
    readiness_wait: "{{ kraken_config.readiness.wait | default(readiness_wait_default) }}"

- name: Set Interval
  set_fact: 
    rep_interval: 20

- name: Setup repetitions
  set_fact:
    repetitions: "{{ (( readiness_wait | int ) / rep_interval | int ) | int }}"

- name: Wait for api server response before continuing
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} get nodes --no-headers=true
  register: rbac_get_nodes_result
  until: "{{ rbac_get_nodes_result.stdout_lines | length }} >= 1 | int"
  retries: "{{ repetitions | int }}"
  delay: "{{ rep_interval | int }}"

- include: bootstrap-default-rbac-policy.yaml
  when: "cluster.kubeAuth.authz.rbac is defined"
