---
- name: Get all managed nodepool descriptions
  command: >
    gcloud compute instances list
      --format="value(networkInterfaces[0].accessConfigs[0].natIP)"
      --filter="metadata.items.key:k2nodepool AND metadata.items.value:{{ item.name }}"
      --project {{ cluster.providerConfig.project }}
  register: node_ips_out
  with_items: "{{ cluster.nodePools }}"

- name: Generate ssh inventory
  template: src=ssh_config.jinja2
    dest="{{ config_base }}/{{ cluster.name }}/ssh_config"