---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate bastion sshd_config writefiles
  template: src=write_files.sshd_config.part.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.write_files.sshd_config.part"
