---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate sshd_config file
  template: src=sshd_config.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.sshd_config"
