---
- name: Create user-data base dict
  set_fact:
    cloud_config: {}

- name: Loop over all nodepools for each cluster
  include: cluster-start.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.0.providerConfig.type == 'cloudinit'