---
apiserver_settings:
  # https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/admin/admission-controllers.md#is-there-a-recommended-set-of-plug-ins-to-use
  admission-control: NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
  alsologtostderr: false
  basic-auth-file: "{{ kubernetes_cert_dir }}/basic_auth.csv"
  bind-address: 0.0.0.0
  client-ca-file: "{{ kubernetes_cert_dir }}/kube-ca.pem"
  cors-allowed-origins: .*
  etcd-servers: "http://{{etcd_private_ip}}:4001"
  # TODO: enable this once we've got a separate etcd instance
  # etcd-servers-overrides: "/events#http://{{etcd_private_ip}}:4001"
  event-ttl: 1h0m0s
  insecure-bind-address: 0.0.0.0
  insecure-port: 8080
  kubelet-timeout: 5s
  log_dir: "{{ kubernetes_log_dir }}/apiserver"
  logtostderr: false
  max-requests-inflight: 400
  profiling: true
  runtime_config: "api/{{kubernetes_api_version}}"
  secure_port: 443
  service-cluster-ip-range: "{{ cluster_ip_range }}"
  tls-cert-file: "{{ kubernetes_cert_dir }}/kube-ca.pem"
  tls-private-key-file: "{{ kubernetes_cert_dir }}/kube-ca-key.pem"
  token-auth-file: "{{ kubernetes_cert_dir }}/known_tokens.csv"
  v: 1