---
- include: generate-oidc-cert.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - a_cluster.kubeAuth.authn.oidc is defined
    - kraken_action == 'up'
    - a_cluster.clusterServices is defined

- include: kill-dns.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - kraken_action == 'down'
    - a_cluster.providerConfig.provider in ['aws']
  static: no

- include: run-dns.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - kraken_action == 'up'
    - a_cluster.providerConfig.provider in ['aws']
  static: no

- include: run-services.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - kraken_action == 'up'
    - a_cluster.helmConfig is defined
  static: no

- include: manage-services.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - kraken_action == 'update'
    - a_cluster.helmConfig is defined
  static: no

- include: kill-services.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - a_cluster.helmConfig is defined
    - kraken_action == 'down'

- include: create-storage-class.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when:
    - kraken_action == 'up'