- set_fact:
    cluster: "{{ a_cluster }}"

- name: Look up and set k8s minor version for this cluster
  set_fact:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"

- name: create kubeconfig entry
  command: >
    {{ kubectl }} config set-cluster {{ cluster.name }}
      --server=https://{{ kraken_endpoint }}
      --certificate-authority={{ config_base | expanduser }}/{{ cluster.name }}/certs/ca.pem
      --embed-certs=true
      --kubeconfig={{ kubeconfig }}

- name: Retrive default user from authn list
  set_fact:
    default_basic_kube_auth: "{{ cluster.kubeAuth.authn.basic | selectattr('user', 'match', '^'+cluster.kubeAuth.authn.default_basic_user+'$') | first }}"

- name: create user entry
  command: >
    {{ kubectl }} config set-credentials {{ cluster.name }}_admin
      --username={{ default_basic_kube_auth.user }}
      --password={{ default_basic_kube_auth.password }}
      --client-certificate={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.crt
      --client-key={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.key
      --embed-certs=true
      --kubeconfig={{ kubeconfig }}

- name: create context entry
  command: >
    {{ kubectl }} config set-context {{ cluster.name }}_context
      --cluster={{ cluster.name }}
      --user={{ cluster.name }}_admin
      --kubeconfig={{ kubeconfig }}

- name: set current context
  command: >
    {{ kubectl }} config use-context {{ cluster.name }}_context
      --kubeconfig={{ kubeconfig }}
