---
- name: Fail if user specified config file does not exist
  fail:
    msg: >-
         The configuration file ({{ config_file }}) cannot be found. Please make sure a file exists and you specified the correct file path.
  when: not config_file | is_file

- name: "Expand ~ paths"
  set_fact:
    config_base: "{{ config_base | expanduser }}"
    config_file: "{{ config_file | expanduser }}"

- name: Load default configuration file
  include_vars:
    file: "{{ role_path }}/files/config.yaml"
    name: kraken_config_defaults

- name: Load user specified configuration file
  include_vars:
    file: "{{ config_file }}"
    name: kraken_config_user

- name: Non-recursively combine and expand the defaults and user configuration
  set_fact:
    kraken_config: "{{ kraken_config_defaults.deployment | combine(kraken_config_user.deployment) | expand_config }}"

- name: Validate the config against the schema
  include: validate-config.yaml

- name: Verify and set global facts
  include: global-setup.yaml

- name: Verify and set per cluster facts
  include: per-cluster-setup.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
