---
- name: Delete the deployment (cluster)
  command: >
    gcloud deployment-manager deployments delete {{ kraken_config.cluster }}-k2-deployment
      --project {{ kraken_config.providerConfig.project }}
      --no-async
      --quiet
  ignore_errors: yes

- name: Query all clusters
  shell: gcloud container clusters list --project {{ kraken_config.providerConfig.project }} | grep {{kraken_config.cluster}}
  register: cluster_check 
  ignore_errors: yes

- name: Delete the cluster
  command: >
    gcloud container clusters delete {{ kraken_config.cluster }} 
      --project {{ kraken_config.providerConfig.project }}
      --zone {{ kraken_config.providerConfig.zone.primaryZone }}
      --no-async
      --quiet
  when: cluster_check|success

