---
- name: Update master, if needed
  command: >
    gcloud container clusters upgrade {{ kraken_config.cluster }}
      --master
      --project {{ kraken_config.providerConfig.project }}
      --zone {{ kraken_config.providerConfig.zone.primaryZone }}
      --no-async
      --quiet
  when: kraken_config.providerConfig.kubeConfig.version is defined

- name: Update nodepools, if needed
  command: >
    gcloud container clusters upgrade {{ kraken_config.cluster }}
      --node-pool {{item.name}}
      --cluster-version {{item.kubeConfig.version}}
      --project {{ kraken_config.providerConfig.project }}
      --zone {{ kraken_config.providerConfig.zone.primaryZone }}
      --no-async
      --quiet
  when: item.kubeConfig.version is defined
  with_items: "{{kraken_config.nodepool}}"
