- name: Generate node units.kraken-worker-ssl.part
  template: src=units.kraken-worker-ssl.part.jinja2
    dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.units.kraken-worker-ssl.part"
  with_items: "{{kraken_config.node}}"

- name: Generate node units.kubelet.part
  template: src=units.kubelet.part.jinja2
    dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.units.kubelet.part"
  with_items: "{{kraken_config.node}}"