---
deployment:
  cluster: krakenCluster
  serviceCidr: 10.32.0.0/12
  serviceDNS: 10.32.0.2
  coreos:
    -
      name: allNodes
      version: current
      channel: stable
      rebootStrategy: off
  keypair:
    -
      name: krakenKey
      publickeyFile: "{{ '~/.ssh/id_rsa.pub' | expanduser}}"
  kubeConfig:
    -
      name: krakenKubeConfig
      version: v1.3.4
      containerConfig: dockerconfig
  containerConfig:
    -
      name: dockerconfig
      version: 1.12.0
      runtime: docker
  fabric:
    provider: flannel
    options:
      Network: 10.128.0.0/10
      SubnetLen: 22
      SubnetMin: 10.128.0.0
      SubnetMax: 10.191.255.255
      Backend:
        Type: vxlan
  provider: aws
  providerConfig:
    resourcePrefix:
    vpc: 10.0.0.0/16
    region: us-west-2
    subnet:
      -
        name: uwswest2a
        az: us-west-2a
        cidr: 10.0.0.0/18
      -
        name: uwswest2b
        az: us-west-2b
        cidr: 10.0.64.0/18
      -
        name: uwswest2c
        az: us-west-2c
        cidr: 10.0.128.0/17
    egressAcl:
      -
        protocol: "-1"
        rule_no: 100
        action: "allow"
        cidr_block: "0.0.0.0/0"
        from_port: 0
        to_port: 0
    ingressAcl:
      -
        protocol: "-1"
        rule_no: 100
        action: "allow"
        cidr_block: "0.0.0.0/0"
        from_port: 0
        to_port: 0
    authentication:
      accessKey:
      accessSecret:
      credentialsFile:
      credentialsProfile:
    ingressSecurity:
      -
        from_port: 22
        to_port: 22
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 8080
        to_port: 8080
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 443
        to_port: 443
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 8094
        to_port: 8094
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 10250
        to_port: 10250
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 10251
        to_port: 10251
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 10252
        to_port: 10252
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 10254
        to_port: 10254
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      -
        from_port: 30000
        to_port: 32767
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
    egressSecurity:
      -
        from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks: ["0.0.0.0/0"]
  nodepool:
    -
      name: etcd
      count: 2
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
        -
          device: sdg
          path: /ephemeral
          forceFormat: false
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "Cluster etcd"
        storage:
          -
            type: ebs_block_device
            opts:
              device_name: sdf
              volume_type: gp2
              volume_size: 100
              delete_on_termination: true
              snapshot_id:
              encrypted: false
          -
            type: ebs_block_device
            opts:
              device_name: sdg
              volume_type: gp2
              volume_size: 10
              delete_on_termination: true
              snapshot_id:
              encrypted: false
      keypair: krakenKey
      coreos: allNodes
    -
      name: etcdEvents
      count: 2
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
        -
          device: sdg
          path: /ephemeral
          forceFormat: false
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "Cluster events etcd"
        storage:
          -
            type: ebs_block_device
            opts:
              device_name: sdf
              volume_type: gp2
              volume_size: 100
              delete_on_termination: true
              snapshot_id:
              encrypted: false
          -
            type: ebs_block_device
            opts:
              device_name: sdg
              volume_type: gp2
              volume_size: 10
              delete_on_termination: true
              snapshot_id:
              encrypted: false
      keypair: krakenKey
      coreos: allNodes
    -
      name: masterNodes
      count: 3
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "Master instances"
        storage:
          -
            type: ebs_block_device
            opts:
              device_name: sdf
              volume_type: gp2
              volume_size: 100
              delete_on_termination: true
              snapshot_id:
              encrypted: false
      keypair: krakenKey
      kubeConfig: krakenKubeConfig
      coreos: allNodes
    -
      name: clusterNodes
      count: 3
      keypair: krakenKey
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "Cluster plain nodes"
        storage:
          -
            type: ebs_block_device
            opts:
              device_name: sdf
              volume_type: gp2
              volume_size: 100
              delete_on_termination: true
              snapshot_id:
              encrypted: false
      kubeConfig: krakenKubeConfig
      coreos: allNodes
    -
      name: specialNodes
      count: 2
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
      keypair: krakenKey
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "Cluster special nodes"
        storage:
          -
            type: ebs_block_device
            opts:
              device_name: sdf
              volume_type: gp2
              volume_size: 100
              delete_on_termination: true
              snapshot_id:
              encrypted: false
      kubeConfig: krakenKubeConfig
      coreos: allNodes
  etcd:
    -
      name: etcd
      clientPorts: [2379, 4001]
      clusterToken: espouse-monger-rarely
      nodepool: etcd
      peerPorts: [2380]
      ssl: true
      version: v3.0.3
      containerConfig: dockerconfig
    -
      name: etcdEvents
      clientPorts: [2381]
      clusterToken: animism-training-chastity
      nodepool: etcdEvents
      peerPorts: [2382]
      ssl: true
      version: v3.0.3
      containerConfig: dockerconfig
  master:
    nodepool: masterNodes
    loadbalancer: cloud
    infra:
      etcd: etcd
    events:
      etcd: etcdEvents
  node:
    -
      name: clusterNodes
      nodepool: clusterNodes
    -
      name: specialNodes
      nodepool: specialNodes
  clusterServices:
    repos:
      -
        name: atlas
        url: http://atlas.cnct.io
    services:
      -
        name: kubedns
        repo: atlas
        chart: kubedns-0.1.0
        values:
          cluster_ip: 10.32.0.2
          dns_domain: krakenCluster.local
