---
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Set kubeconfig fact
  set_fact:
    kubefn: "{{ config_base }}/{{ cluster.name }}/admin.kubeconfig"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"
  vars:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Ensuring fabric directory exists
  file:
    path: "{{ config_base }}/{{ cluster.name }}/fabric"
    state: directory

- name: Leagacy non-versioned fabric check
  set_fact:
    fabricConfigVal: "{{ cluster.fabricConfig }}"
  when: cluster.fabricConfig.kind == 'fabric'

- name: Load the correct fabric config for the kuberenetes version
  set_fact:
    fabricConfigVal: "{{ cluster.fabricConfig.kubeVersion.versions[ kubernetes_minor_version ] if cluster.fabricConfig.kubeVersion.versions[ kubernetes_minor_version ] is defined else cluster.fabricConfig.kubeVersion.default }}"
  vars:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"
  when: cluster.fabricConfig.kind == 'versionedFabric'

- name: Generate weave deployment file
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/fabric/weave.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/weave.yaml.part.jinja2"
      - weave.yaml.part.jinja2

- name: Generate Network Namespace Fie
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/fabric/namespace.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/namespace.yaml.part.jinja2"
      - namespace.yaml.part.jinja2

- name: Deploy Networking Namespace
  command: >
    {{ kubectl }} --kubeconfig={{ kubefn }} apply -f {{ config_base }}/{{ cluster.name }}/fabric/namespace.yaml --record
  when: not ( dryrun | bool )

- name: Deploy weave daemonset
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} apply -f {{ config_base }}/{{ cluster.name }}/fabric/weave.yaml --namespace=kube-networking --record
  when: not (dryrun | bool)
