---
controller_manager_settings:
  address: 0.0.0.0
  alsologtostderr: false
  concurrent-endpoint-syncs: 5
  concurrent-rc-syncs: 5
  deleting-pods-burst: 10
  kubeconfig: "{{ kubernetes_cert_dir }}/system:controller_manager/kubeconfig"
  log_dir: "{{ kubernetes_log_dir }}/controller-manager"
  logtostderr: false
  master: "{{access_scheme}}://{{ master_private_ip }}:{{access_port}}"
  namespace-sync-period: 5m0s
  node-monitor-grace-period: 40s
  node-monitor-period: 5s
  node-startup-grace-period: 1m0s
  node-sync-period: 10s
  pod-eviction-timeout: 1m
  port: 10252
  profiling: true
  pvclaimbinder-sync-period: 10s
  register-retry-count: 10
  resource-quota-sync-period: 20s
  root-ca-file: "{{ kubernetes_cert_dir }}/kube-ca.pem"
  service-account-private-key-file: "{{ kubernetes_cert_dir }}/kube-ca-key.pem"
  service-sync-period: 5m0s
  v: 1