---
- name: determine profile name
  set_fact:
    cluster: "{{ cluster |combine({'providerConfig':{'authentication':{'credentialsProfile': 'default'}}}, recursive=True) }}"
  when:
    cluster.providerConfig.authentication.credentialsProfile | is_empty

- name: set accessKey if unset and credentialsFile set
  set_fact:
    cluster: "{{ cluster |combine({'providerConfig':{'authentication':{'accessKey': lookup('ini', 'aws_access_key_id section=' + cluster.providerConfig.authentication.credentialsProfile + ' file=' + cluster.providerConfig.authentication.credentialsFile)}}}, recursive=True)}}"
  when:
    - cluster.providerConfig.authentication.accessKey | is_empty
    - not (cluster.providerConfig.authentication.credentialsFile | is_empty)

- name: set accessSecret if unset and credentialsFile set
  set_fact:
    cluster: "{{ cluster | combine({'providerConfig':{'authentication':{'accessSecret': lookup('ini', 'aws_secret_access_key section=' + cluster.providerConfig.authentication.credentialsProfile + ' file=' + cluster.providerConfig.authentication.credentialsFile)}}}, recursive=True)}}"
  when:
    - cluster.providerConfig.authentication.accessSecret | is_empty
    - not (cluster.providerConfig.authentication.credentialsFile | is_empty)

- name: set securityToken if unset and credentialsFile set
  set_fact:
    cluster: "{{ cluster | combine({'providerConfig':{'authentication':{'securityToken': lookup('ini', 'aws_session_token section=' + cluster.providerConfig.authentication.credentialsProfile + ' file=' + cluster.providerConfig.authentication.credentialsFile)}}}, recursive=True)}}"
  when:
    - cluster.providerConfig.authentication.securityToken is defined
    - cluster.providerConfig.authentication.securityToken | is_empty
    - not (cluster.providerConfig.authentication.credentialsFile | is_empty)
