---
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Set kubeconfig fact
  set_fact:
    kubefn: "{{ config_base }}/{{ cluster.name }}/admin.kubeconfig"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"
  vars:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Ensuring fabric directory exists
  file:
    path: "{{ config_base }}/{{ cluster.name }}/fabric"
    state: directory

- name: Leagacy non-versioned fabric check
  set_fact:
    fabricConfigVal: "{{ cluster.fabricConfig }}"
  when: cluster.fabricConfig.kind == 'fabric'

- name: Load the correct fabric config for the kuberenetes version
  set_fact:
    fabricConfigVal: "{{ cluster.fabricConfig.kubeVersion.versions[ kubernetes_minor_version ] if cluster.fabricConfig.kubeVersion.versions[ kubernetes_minor_version ] is defined else cluster.fabricConfig.kubeVersion.default }}"
  vars:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"
  when: cluster.fabricConfig.kind == 'versionedFabric'

- name: Generate canal RBAC policy file
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/auth/rbac-canal-policy.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/rbac-canal-policy.yaml.jinja2"
      - rbac-canal-policy.yaml.jinja2
  when: "cluster.kubeAuth.authz.rbac is defined"

- name: Generate Network Namespace Fie
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/fabric/namespace.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/namespace.yaml.part.jinja2"
      - namespace.yaml.part.jinja2

- name: Generate canal deployment file
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/fabric/canal.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/canal.yaml.part.jinja2"
      - canal.yaml.part.jinja2

- name: Generate canal configuration file
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/fabric/config.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/config.yaml.part.jinja2"
      - config.yaml.part.jinja2

- name: Deploy Networking Namespace
  command: >
    {{ kubectl }} --kubeconfig={{ kubefn }} apply -f {{ config_base }}/{{ cluster.name }}/fabric/namespace.yaml --record
  when: not ( dryrun | bool )

- name: Deploy canal RBAC policy
  command: >
    {{ kubectl }} --kubeconfig={{ kubefn }} apply -f {{ config_base }}/{{ cluster.name }}/auth/rbac-canal-policy.yaml --record
  register: job_rbac_canal_results
  when:
    - "cluster.kubeAuth.authz.rbac is defined"
    - not ( dryrun | bool )

- name: Deploy canal configuration
  command: >
    {{ kubectl }} --kubeconfig={{ kubefn }} apply -f {{ config_base }}/{{ cluster.name }}/fabric/config.yaml --namespace=kube-networking --record
  when: not ( dryrun | bool )

- name: Deploy canal daemonset
  command: >
    {{ kubectl }} --kubeconfig={{ kubefn }} apply -f {{ config_base }}/{{ cluster.name }}/fabric/canal.yaml --namespace=kube-networking --record
  when: not ( dryrun | bool )
